### ISSUE TITLE
configure: error: not found

### ISSUE THREAD

**Issue by hhbgk** [seveas/atftp#1]
Hi , thanks for your projects. I have issues build with Android NDK:

``` bash
checking for pthread_create in -lpthread... no
configure: error: not found
```

Can I disable checking pthread_create ? and how to?
thanks in advance.

**Comment by seveas** [comment]
Hi @hhbgk,

atftp isn't my project, this is merely a copy I put on github to share some modifications I made. I have no idea about your question, maybe ask at the atftp sourceforge project.
